In [31]:
from sklearn import svm, datasets
iris = datasets.load_iris()
import numpy as np

In [3]:
import pandas as pd
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df[47:52]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
47                4.6               3.2                1.4               0.2   
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   

        flower  
47      setosa  
48      setosa  
49      setosa  
50  versicolor  
51  versicolor

## Approach 1: Use train_test_split and manually tune parameters by trial and error

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3)

In [24]:
## We assumed that SVM as best model
model = svm.SVC(kernel='rbf', C=30, gamma='auto')
model.fit(X_train, y_train)
model.score(X_test, y_test) 

## Here the score is changing based on the test, train selection, so we cant rely on this-- we go for K-fold valiation

0.9555555555555556

## Approach 2: Use K Fold Cross validation

**Manually try suppling models with different parameters to cross_val_score function with 5 fold cross validation**


In [26]:
from sklearn.model_selection import cross_val_score

In [27]:
cross_val_score(svm.SVC(kernel='linear', C=10, gamma='auto'), iris.data, iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [28]:
cross_val_score(svm.SVC(kernel='rbf', C=10, gamma='auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [29]:
cross_val_score(svm.SVC(kernel='rbf', C=20, gamma='auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

**Above approach is tiresome and very manual. We can use for loop as an alternative**

In [33]:
kernels = ['rbf','linear']
C = [1,10,20]
avg_score = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel=kval, C=cval, gamma='auto'), iris.data, iris.target, cv=5)
        avg_score[kval + '_' + str(cval)] = np.average(cv_scores)
avg_score

## this method too has some issue -- if we have 4 parameters we have to run too many iterations
## thats why we use the Grid Search CV by sklearn

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

## Approach 3: Use GridSearchCV

In [38]:
## importing the GridSearchCV
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svm.SVC(gamma='auto'), { ## here we are providing the model and the gamma value
    'C':[1,10,20], ## In parameter grid we are providing the C and Kernel
    'kernel':['rbf', 'linear']
}, cv=5, return_train_score=False)#here we are giving the required cross validations, we provided it as CV=5
clf.fit(iris.data, iris.target)
clf.cv_results_ ## we got multiple results
## CV results are not easy to view, but we can convert the results into a dataframe

{'mean_fit_time': array([0.0010283 , 0.00712605, 0.00201349, 0.00139923, 0.00159888,
        0.00312572]),
 'std_fit_time': array([0.00128818, 0.00872918, 0.00402699, 0.00048973, 0.00079944,
        0.00625143]),
 'mean_score_time': array([0.00123053, 0.0005991 , 0.00313334, 0.00119929, 0.00101008,
        0.        ]),
 'std_score_time': array([0.00150791, 0.0011982 , 0.00512731, 0.00039969, 0.00063268,
        0.        ]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],


In [40]:
## making the dataframe for the cv results
df = pd.DataFrame(clf.cv_results_)
df ## we have successfully converted the result into a DF

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001028      0.001288         0.001231        0.001508       1   
1       0.007126      0.008729         0.000599        0.001198       1   
2       0.002013      0.004027         0.003133        0.005127      10   
3       0.001399      0.000490         0.001199        0.000400      10   
4       0.001599      0.000799         0.001010        0.000633      20   
5       0.003126      0.006251         0.000000        0.000000      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [41]:
### checking the useful columns
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [42]:
dir(clf) ## to check the available parameters

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 '_validate_params',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 '

In [43]:
clf.best_score_

0.9800000000000001

In [45]:
clf.best_params_ ## it gave us best parameters

{'C': 1, 'kernel': 'rbf'}

one issue with Gird search cv - is the computation cost\
current dataset is limited..

What is we have millions of Datapoints?\
    then for parameters we have so many values\
    Ex - for calculating the range of 50 cross validation -- the computation cost will get high which means it takes much of the time

To tackle this computation problem sklearn library comes up with randomized search cv

# Randomized search CV

it will not try every single permutation and combination of parameters, but it will try random parameters values\
we can choose what those iteration could be

In [68]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma='auto'), {
        'C':[1,10,20],
        'kernel':['rbf','linear']
    },
    cv = 5,
    return_train_score = False,
    n_iter=2 ## it will try only 2 combinations
)

rs.fit(iris.data, iris.target)
pd.DataFrame(rs.cv_results_)[['param_C', 'param_kernel', 'mean_test_score']]

## we got 2 results

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1      20          rbf         0.966667

### Till now we worked of about hyperperameter tuning, How about different models with different hyperparameters?


In [69]:
## importing the require libraries of algorithms
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [86]:
# Defining  the model parameters for Grid parameters -- we used 3 models

model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10]
        }
    }
}

In [87]:
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.960000        {'n_estimators': 1}
2  logistic_regression    0.966667                   {'C': 5}