## Savingt the model using

> 1) pickle
> 2) sklearn joblib

In [1]:
## code form Linear Regression

import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv('D:\\Data Science\\Code basics\\py-master\\ML\\4_save_model\\homeprices.csv')
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [5]:
model.coef_

array([135.78767123])

In [6]:
model.intercept_

180616.43835616432

In [7]:
model.predict([[5000]])

C:\Users\Ajith\anaconda3\envs\geo_env\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

## Save Model To a File Using Python Pickle

In [10]:
import pickle ## it allows to serialize the file

In [12]:
with open ('model_pickle', 'wb') as f:
    pickle.dump(model,f)  ## it creates a binary file

In [13]:
## can use the same model
with open ('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [15]:
mp.predict([[5000]])

C:\Users\Ajith\anaconda3\envs\geo_env\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [16]:
### the saved model can be shared

In [18]:
### Using the Joblib
# If the model consist of large numpy array, its better to use the joblib

In [21]:
import joblib

In [23]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [24]:
## Load the model

In [25]:
mj = joblib.load('model_joblib')

In [26]:
mj.predict([[5000]])

C:\Users\Ajith\anaconda3\envs\geo_env\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [28]:
mj.coef_

array([135.78767123])

In [30]:
mj.intercept_

180616.43835616432