In [1]:
import numpy as np

In [2]:
# we have y 'predicted' & 'true' values here
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

# Implement Mean Square Error

In [3]:
def mae(y_true, y_predicted):
    total_error = 0
    # run for loop in 2 arrays
    for yt, yp in zip(y_true, y_predicted):
        #print(yt, yp)
        #for absolute difference, in python there is a function named abs
        total_error += abs(yt - yp)
    print("total_error : ", total_error)
    # for getting the mean of the errors
    mae = total_error / len(y_true)
    print("MAE : ", mae)
    return mae

In [4]:
mae(y_true, y_predicted)

total_error :  2.5
MAE :  0.5


0.5

## Same function using numpy

In [5]:
# since we have the numpy array, we can directly subtract the values
y_predicted - y_true

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [6]:
# we can use the abs with numpy
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [7]:
# for taking the mean
np.mean(np.abs(y_predicted - y_true))

0.5

In [8]:
# for getting total error
np.sum(np.abs(y_predicted - y_true))

2.5

In [9]:
# Implement the Log loss or Binary cross entropy
np.log([0]) # log([0]) is not defined
# so when we have log([0]) we have to take a value which is close to 0

C:\Users\Admin\AppData\Local\Temp\ipykernel_11588\2997779966.py:2: RuntimeWarning: divide by zero encountered in log
  np.log([0]) # log([0]) is not defined


array([-inf])

In [10]:
# value close to 0
np.log([0.00000000000000001])

array([-39.14394658])

In [11]:
# In our Log_loss function, we have to replace the 0 value with close to 0
# in the log loss formula, we have 1-y
# if the y = 1, then the final value will be 0, so we have to fix that
# for fixing that we will use eplison
eplison = 1e-15

In [12]:
y_predicted

array([1, 1, 0, 0, 1])

In [13]:
# in y_predicted 
# we will replace 0 with value close to 0 --> e-15
# we will replace 1 with value close to 1 --> 0.9999999999999

y_predicted_new = [max(i, eplison) for i in y_predicted]
y_predicted_new
# it replaced 0 with 1e-15

[1, 1, 1e-15, 1e-15, 1]

In [14]:
y_predicted_new = [min(i, 1-eplison) for i in y_predicted_new]
# here eplison is close to 0, and 1-eplison is close to 1 or which is inverse of close to 0
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [15]:
# convert the y_predicy_predicted_new as numpy array
y_predicted_new = np.array(y_predicted_new)
# apply the log function for the new array which is converted to numpy array
np.log(y_predicted_new)
# We got the converted log of the numbers

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [16]:
# if we directly convert the y_predicted into log, we will end up with error, where we will get the value of infinity
np.log(y_predicted)
# here the '0' value is considered as -infinity which is incorrect

C:\Users\Admin\AppData\Local\Temp\ipykernel_11588\3573581772.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

# Writing the log loss function by using the numpy

In [18]:
# refer the log_loss formula at the notes
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [21]:
# writing altogether
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [22]:
log_loss(y_true, y_predicted)

17.2696280766844