In [1]:
import tensorflow as tf

In [2]:
# Create a simple dataset from list
daily_sales_numbers = [21, 22, -108, 31, -1, 32, 34,31]

tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers) # Building the tf_dataset from a list
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [3]:
# For knowing the content in the dataset, we can Iterate through it
for sales in tf_dataset:
    print(sales.numpy())

21
22
-108
31
-1
32
34
31


In [4]:
#Iterate through first n elements in tf dataset
for sales in tf_dataset.take(3):
    print(sales.numpy())

21
22
-108


In [5]:
# Filter sales numbers that are < 0
tf_dataset = tf_dataset.filter(lambda x: x>0)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
31
32
34
31


In [6]:
# Convert sales numbers from USA dollars ($) to Indian Rupees (INR) Assuming 1->72 conversation rate
tf_dataset = tf_dataset.map(lambda x: x*72) # map function takes individual element and iterate through it
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

1512
1584
2232
2304
2448
2232


In [7]:
# Shuffe
tf_dataset = tf_dataset.shuffle(2)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

1512
2232
1584
2304
2448
2232


In [8]:
# Batching
for sales_batch in tf_dataset.batch(2):
    print(sales_batch.numpy())

[1584 1512]
[2304 2232]
[2448 2232]


In [9]:
# Perform all of the above operations in one shot
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

tf_dataset = tf_dataset.filter(lambda x: x>0).map(lambda y: y*72).shuffle(2).batch(2)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

[1584 1512]
[2304 2232]
[2448 2232]


In [10]:
# Load Images
images_ds = tf.data.Dataset.list_files('D:/Data Science/Code basics/py-master/deep-learning-keras-tf-tutorial-master/44_tf_data_pipeline/images/*/*', 
                                       shuffle=False)
# Printing the 1st 3 file path
for file in images_ds.take(3):
    print(file.numpy())

b'D:\\Data Science\\Code basics\\py-master\\deep-learning-keras-tf-tutorial-master\\44_tf_data_pipeline\\images\\cat\\20 Reasons Why Cats Make the Best Pets....jpg'
b'D:\\Data Science\\Code basics\\py-master\\deep-learning-keras-tf-tutorial-master\\44_tf_data_pipeline\\images\\cat\\7 Foods Your Cat Can_t Eat.jpg'
b'D:\\Data Science\\Code basics\\py-master\\deep-learning-keras-tf-tutorial-master\\44_tf_data_pipeline\\images\\cat\\A cat appears to have caught the....jpg'


In [13]:
## Using the Shuffle

images_ds = images_ds.shuffle(200)
for file in images_ds.take(3):
    print(file.numpy())

b'D:\\Data Science\\Code basics\\py-master\\deep-learning-keras-tf-tutorial-master\\44_tf_data_pipeline\\images\\cat\\International Cat Care _ The ultimate....jpg'
b'D:\\Data Science\\Code basics\\py-master\\deep-learning-keras-tf-tutorial-master\\44_tf_data_pipeline\\images\\dog\\Most Popular Breeds \xe2\x80\x93 American Kennel Club.jpg'
b'D:\\Data Science\\Code basics\\py-master\\deep-learning-keras-tf-tutorial-master\\44_tf_data_pipeline\\images\\cat\\Are Cats Domesticated_ _ The New Yorker.jpg'


In [14]:
# Create a list class
class_names = ["cat","dog"]

In [15]:
# Checking the image count
image_count = len(images_ds)
image_count

130

In [16]:
# Checking the data type
type(images_ds)

tensorflow.python.data.ops.shuffle_op._ShuffleDataset

In [17]:
## Train test split
train_size = int(image_count*0.8)
train_ds = images_ds.take(train_size)
test_ds = images_ds.skip(train_size)

In [18]:
len(train_ds)

104

In [19]:
len(test_ds)

26

In [20]:
# for getting the label form the path
s = "images\\dog\\20 Reasons Why Cats Make the Best Pets....jpg"
s.split('\\')[-2]

'dog'

In [21]:
# We have to get the label from the image path, since the folder categorized as per the requirement
def get_label(file_path):
    import os
    parts = tf.strings.split(file_path, os.path.sep)
    return parts[-2]

In [22]:
get_label("images\\dog\\20 Reasons Why Cats Make the Best Pets....jpg")

<tf.Tensor: shape=(), dtype=string, numpy=b'dog'>

In [27]:
# make a function to make the X part for training
def process_image(file_path):
    label = get_label(file_path)
    img = tf.io.read_file(file_path) # load the raw data from the file as a string
    img = tf.image.decode_jpeg(img) # decode the Image
    img = tf.image.resize(img, [128, 128]) # Resize the image
    return img, label # here X_train --> img ,, y_train -->label

In [23]:
# Check the train_ds
for t in train_ds.take(4):
    print(t.numpy())

b'D:\\Data Science\\Code basics\\py-master\\deep-learning-keras-tf-tutorial-master\\44_tf_data_pipeline\\images\\cat\\The Science-Backed Benefits of Being a....jpg'
b'D:\\Data Science\\Code basics\\py-master\\deep-learning-keras-tf-tutorial-master\\44_tf_data_pipeline\\images\\dog\\List of dog breeds - Wikipedia.jpg'
b'D:\\Data Science\\Code basics\\py-master\\deep-learning-keras-tf-tutorial-master\\44_tf_data_pipeline\\images\\dog\\The 25 Cutest Dog Breeds - Most....jpg'
b'D:\\Data Science\\Code basics\\py-master\\deep-learning-keras-tf-tutorial-master\\44_tf_data_pipeline\\images\\dog\\What makes dogs so special and....jpg'


In [24]:
# For getting the label from the path
for label in train_ds.map(get_label):
    print(label)

tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=

In [34]:
# Call the process_image function
train_ds = train_ds.map(process_image)
for img,label in train_ds.take(3):
    print('Image: ', img)
    print('label: ',label)

Image:  tf.Tensor(
[[[225.03125  187.03125  168.03125 ]
  [224.75684  186.75684  167.75684 ]
  [210.1377   171.1377   156.1377  ]
  ...
  [ 85.81348  111.81348  110.81348 ]
  [116.31641  147.3164   150.3164  ]
  [106.7959   140.7959   142.7959  ]]

 [[219.22461  181.22461  162.22461 ]
  [222.43066  183.43066  166.43066 ]
  [213.56738  174.56738  157.56738 ]
  ...
  [ 97.66211  127.47461  129.38086 ]
  [117.27734  148.27734  151.27734 ]
  [116.14844  150.14844  152.14844 ]]

 [[224.79297  186.79297  167.79297 ]
  [224.97168  185.97168  168.97168 ]
  [209.98926  170.98926  155.98926 ]
  ...
  [104.08496  135.89746  134.99121 ]
  [114.87891  148.8789   150.8789  ]
  [114.331055 148.33105  150.33105 ]]

 ...

 [[211.53223  225.43848  234.34473 ]
  [204.75293  219.56543  226.65918 ]
  [235.26367  240.4248   246.45117 ]
  ...
  [ 62.453125  57.623047  38.623047]
  [ 79.75098   74.75098   55.750977]
  [ 73.05859   66.05859   47.058594]]

 [[219.45605  229.1875   238.84375 ]
  [218.45117  231.

In [32]:
# write a function for scaling
def scale(image, label):
    return image/255, label

In [35]:
train_ds = train_ds.map(scale)

for image, label in train_ds.take(5):
    print("******Image: ", image.numpy()[0][0])
    print("******Label: ", label.numpy())

******Image:  [0.50351036 0.46697664 0.25398403]
******Label:  b'dog'
******Image:  [0.3125766  0.34394914 0.35571384]
******Label:  b'dog'
******Image:  [0.13370098 0.34154412 0.30232844]
******Label:  b'dog'
******Image:  [0.27450982 0.23137255 0.20784314]
******Label:  b'cat'
******Image:  [0.38039216 0.16470589 0.52156866]
******Label:  b'cat'
