Here is the page that has list of all available bert models on tensorflow hub that one can download and make use of.

https://tfhub.dev/google/collections/bert/1

Here is the information on basic uncased BERT model,

https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4

It uses L=12 hidden layers (i.e., Transformer blocks), a hidden size of H=768, and A=12 attention heads. This model has been pre-trained for English on the Wikipedia and BooksCorpus.

In [2]:
!pip install tensorflow_text

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 27.1 MB/s eta 0:00:00


In [3]:
import tensorflow_hub as hub
import tensorflow_text as text

In [4]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [5]:
# building a function for Hub to refer in future
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [6]:
# testing the model foer understanding

text_test = ['nice movie indeed','I love python programming']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [7]:
# Lets look at individual elements in the dictionary
text_preprocessed['input_mask']

# here the shape of 2 x 128 -- for the 2 sentence which we provided -- 128 is the maximum lengeth of the sentence
# Here at the begining we have 5 1's this because the BERT initiate 'CLS nice movie indeed SEP'

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [8]:
text_preprocessed['input_type_ids'] # our case it is 0's since we are not using them

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [9]:
text_preprocessed['input_word_ids']
# 'CLS nice movie indeed SEP' -- we have unique id's for each word

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [11]:
# after the preprocessing we have to create another layer for encoded url
bert_model = hub.KerasLayer(encoder_url)
# here the bert model acts like a function which we can call

In [12]:
bert_results = bert_model(text_preprocessed) ## it will have the word embeddings

In [13]:
bert_results.keys()

dict_keys(['default', 'sequence_output', 'pooled_output', 'encoder_outputs'])

In [15]:
bert_results['pooled_output'] # it is the embedding for entire sentence

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.7917742 , -0.21411917,  0.49769565, ...,  0.24465217,
        -0.47334474,  0.8175871 ],
       [-0.9171231 , -0.4793516 , -0.7865695 , ..., -0.6175173 ,
        -0.7102685 ,  0.92184305]], dtype=float32)>

In [17]:
bert_results['sequence_output'] ## It will have the embeddings for each word

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292052,  0.0856782 ,  0.14476837, ..., -0.09677092,
          0.08722129,  0.07711072],
        [ 0.1783944 , -0.19006099,  0.5034946 , ..., -0.05869839,
          0.32717127, -0.15578558],
        [ 0.18701541, -0.43388733, -0.48875114, ..., -0.15502825,
          0.00145149, -0.24470972],
        ...,
        [ 0.1208304 ,  0.12884238,  0.4645356 , ...,  0.07375551,
          0.17441969,  0.16522141],
        [ 0.07967842, -0.01190668,  0.5022541 , ...,  0.13777801,
          0.210022  ,  0.00624551],
        [-0.0721268 , -0.28303453,  0.5903342 , ...,  0.47551954,
          0.16668472, -0.08920333]],

       [[-0.07900575,  0.3633509 , -0.21101615, ..., -0.17183736,
          0.16299713,  0.6724265 ],
        [ 0.27883476,  0.43716246, -0.35764748, ..., -0.04463608,
          0.38315183,  0.58879906],
        [ 1.2037674 ,  1.0727015 ,  0.484087  , ...,  0.2492104 ,
          0.40730947,  0.4048182 ],
        ...,

In [16]:
len(bert_results['encoder_outputs'])

12

Since we are using BERT base model it has 12 encoder layers, that's why above the length of encoder_output is 12. Read more about purpose of each element here: https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4

In [18]:
bert_results['encoder_outputs'][-1] == bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>

In [19]:
bert_results['encoder_outputs']

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.1290142 ,  0.00644748, -0.03614981, ...,  0.04999622,
           0.0614919 , -0.02657544],
         [ 1.1753383 ,  1.2140787 ,  1.1569978 , ...,  0.11634371,
          -0.35855392, -0.4049018 ],
         [ 0.03859041,  0.53870016, -0.2108976 , ...,  0.21858224,
           0.7260168 , -1.1158608 ],
         ...,
         [-0.0758702 , -0.25421935,  0.70755106, ...,  0.50541997,
          -0.18878675,  0.1502836 ],
         [-0.16066593, -0.2808966 ,  0.5759706 , ...,  0.5275857 ,
          -0.11141382,  0.02887538],
         [-0.04428159, -0.20279583,  0.5909351 , ...,  0.81338346,
          -0.3907584 , -0.02601748]],
 
        [[ 0.18903565,  0.02752538, -0.06513739, ..., -0.00620211,
           0.15053883,  0.03165444],
         [ 0.5916148 ,  0.75891393, -0.07240677, ...,  0.6190399 ,
           0.8292891 ,  0.16161975],
         [ 1.446083  ,  0.4460266 ,  0.40990236, ...,  0.48255914,
           0.62691176,  0.13