## Importing the necciary libraries

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [3]:
## Logistic Regression
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test,y_test)

## we got LR accuracy of 95%

C:\Users\Ajith\anaconda3\envs\geo_env\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9537037037037037

In [4]:
## SVM

svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)
## we got SVM accuracy of 98%

0.9888888888888889

In [5]:
## Random Forest

rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

## ## we got RF accuracy of 96%

0.9703703703703703

In [6]:
### for above 3 algorithms we manually run them and checked their score of accuracy, when we do resample the score changes due to change in the sample
### which changes the performance of the models
### We can't say that, running the models one time and say the score, we have to run the test multiple times

# KFold cross validation


In [7]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3) ## mentioning that how many folds to create
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
## for using the KFOLD in the example dataset
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index) ## We got the split of the data

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


# Using the Kfold for the digits example

### Option 1 of using the Kfold

In [9]:
## for simplifying the things we make a function for executing models
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [10]:
## Using the KFold
from sklearn.model_selection import StratifiedKFold ## StratifiedKFold better for dividing uniformly
folds = StratifiedKFold(n_splits=3)

In [11]:
## Preparing the scores array
scores_logistic = []
scores_svm = []
scores_rf = []

In [12]:
for train_index, test_index in kf.split(digits.data):
    X_train,X_test, y_train, y_test = digits.data[train_index], digits.data[test_index],\
                                        digits.target[train_index], digits.target[test_index]
    ## measure the performance, since we set as 3 folds the for loop execute for 3 times
    scores_logistic.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))    

C:\Users\Ajith\anaconda3\envs\geo_env\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Ajith\anaconda3\envs\geo_env\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#log

In [13]:
scores_logistic

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [14]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [15]:
scores_rf

[0.9282136894824707, 0.9465776293823038, 0.9148580968280468]

### Option 2 of using Kfold
### Cross validation of score function

In [16]:
from sklearn.model_selection import cross_val_score

In [17]:
avg_lr = cross_val_score(LogisticRegression(), digits.data, digits.target,cv=3)

C:\Users\Ajith\anaconda3\envs\geo_env\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Ajith\anaconda3\envs\geo_env\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#log

In [18]:
avg_SVC = cross_val_score(SVC(), digits.data, digits.target, cv=3)

In [19]:
avg_rf = cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=3)

#### Checking the avverage score

In [20]:
np.average(avg_lr)

0.9265442404006677

In [21]:
np.average(avg_rf)

0.9365609348914857

In [22]:
np.average(avg_SVC)

0.9699499165275459

## Parameter tunning for RF using k fold cross validation

In [23]:
np.average(cross_val_score(RandomForestClassifier(n_estimators=5), digits.data, digits.target,cv=3))

0.8430717863105176

In [24]:
np.average(cross_val_score(RandomForestClassifier(n_estimators=15), digits.data, digits.target,cv=3))

0.9237618252643295

In [25]:
np.average(cross_val_score(RandomForestClassifier(n_estimators=35), digits.data, digits.target,cv=3))

0.9315525876460767

In [26]:
np.average(cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target,cv=3))

0.9376739009460211

In [27]:
np.average(cross_val_score(RandomForestClassifier(n_estimators=60), digits.data, digits.target,cv=3))

0.9387868670005565

In [28]:
np.average(cross_val_score(RandomForestClassifier(n_estimators=70), digits.data, digits.target,cv=3))

0.9398998330550917