In [1]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
#Why we use numpy insted of list?

'''Because numpy use
        1)Less Memory
        2) Fast Operation
        3) Convinient usage'''


'Because numpy use\n        1)Less Memory\n        2) Fast Operation\n        3) Convinient usage'

In [3]:
import numpy as np
import sys
import time

#Comparision b/w numpy and python-list
l = range(1000)
print(sys.getsizeof(5)*len(l))

array = np.arange(1000)
print(array.size*array.itemsize)

'''
    for list it takes - 28000 bytes
    for an array it takes -- 4000 bytes
'''

28000
4000


In [16]:
SIZE = 1000000

l1= range(SIZE)
l2= range(SIZE)

a1=np.arange(SIZE)
a2=np.arange(SIZE)

#Python_List
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took: ",(time.time()-start)*1000)

#numpy array
start=time.time()
result = a1+a1
print("numpy took:", (time.time()-start)*1000)

'''
    Here we have used to add the range of 1000 integers for comparition bw list and numpy
    for addind those thngs
        list took -- 190.72604179382324 ms
        numpy took -- 15.626192092895508 ms
'''

python list took:  193.3267116546631
numpy took: 15.624761581420898


'\n    Here we have used to add the range of 1000 integers for comparition bw list and numpy\n    for addind those thngs\n        list took -- 190.72604179382324 ms\n        numpy took -- 15.626192092895508 ms\n'

In [19]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(a1+a2)
print(a2-a1)
print(a1/a2)
print(a1*a2)

[5 7 9]
[3 3 3]
[0.25 0.4  0.5 ]
[ 4 10 18]


In [28]:
#Numpy tutorial -- basic array operation

a=np.array([1,2,3]) # 1-D array

#2-D array
a=np.array([[1,2],[3,4],[5,6]])
print(a.ndim)#To know how many dimensions in the array

print(a.itemsize)#print's byte size of each of these elements
print(a.dtype)#print's data type of the array -- here it is  dtype('int32')

a=np.array([[1,2],[3,4],[5,6]], dtype=np.float64)#since we decleare it as a float,it will take the 8 byte size to store the data
print(a.itemsize) #it will return the size as "8"


2
4
int32
8


In [32]:
print(a.size) #Shows the total number of elemets in the array
print(a.shape) #Shows the column and rows in the array
a=np.array([[1,2],[3,4],[5,6]], dtype=complex) #will create an array with complex numbers
print(a)


6
(3, 2)
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]


In [42]:
#to initilize an array with zero
print(np.zeros((3,4))) #here we have to give the dimension of the array and it will generate the array with zeros with given dimendimension 
print(np.ones((3,4)))# it will create the array with 1's


l=range(5)#range function in python for list
print(l)

print(np.arange(1,5))#range function for Numpy


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
range(0, 5)
[1 2 3 4]


In [49]:
a=np.arange(1,5,2) 
'''to create a array with steps of 2 numbers - 

means it will create the array in a manner which skips a number and prints next

here in (1,5,2) -- 1,5 are the range of the array and the 2 is the step
'''
print(a)


#Linspace
a=np.linspace(1,5,10) #this will create 10 numbers bw 1 and 5 which are all linearly spaced
print(a)

a=np.linspace(1,5,5) #this will create 5 numbers bw 1 and 5 which are all linearly spaced
print(a)

[1 3]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
[1. 2. 3. 4. 5.]


In [58]:
a=np.array([[1,2],[3,4],[5,6]])
#print(a)
#print(a.shape)
print(a.reshape(2,3))# To change the dimension of the array
#print(a.shape)
print(a.reshape(6,1))# To change the dimension of the array
#print(a.shape)
#print (a)

print(a.ravel()) #To make the array in one dimension -- it will not change the original array - it will creat new one so have to assign a variable

print(a)


[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [72]:
#Maths in numpy

print(a)
print(a.min())
print(a.max())
print(a.sum())


#Axis function -- use to take the numbers from the given axis
#here - columns are called as axis 0 and rows are called as axis 1

print(a.sum(axis=0))
print(a.sum(axis=1))


# for square root
print(np.sqrt(a))

#for standard deviation
print("Standard Deviation",np.std(a))

a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a+b)
print(a*b)
print(a.dot(b))#it will print matrix product of the array

[[1 2]
 [3 4]]
1
4
10
[4 6]
[3 7]
[[1.         1.41421356]
 [1.73205081 2.        ]]
Standard Deviation 1.118033988749895
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [83]:
#Numpy tutorial; -- slicing/ stacking arrays, indexing with boolean arrays
'''
Topics covered
    1) Indexing and slicing
    2) Iterating through arrays
    3) Stacking together two arrays
    Indexing with boolean arrays
'''

#Indexing and Slicing

#in a list we do
n=[6,7,8]
print(n[0:2])
print(n[-1])


#In a numpy aray
a=np.array([6,7,8])
print(a[0:2])
print(a[-1])

#for a multidimentional array
a=np.array([[6,7,8],[1,2,3],[9,3,2]])
print(a)
print(a[1,2])# it will print the value at 1st row and 2nd column -- note - while counting 0 is included
print(a[0:2,2])# it will print the numpers in the 0th row and 1st row at the 2nd column,,, so here we will get 2 numbers
print(a[-1])#prints the last element in the array, i.e the last row in the array
print(a[-1,0:2])# it will print last row and the 1st 2 columns - we will get 2 numbers

print(a[:,1:3])# it will take all the rows and 2nd and and 3rd colums

[6, 7]
8
[6 7]
8
[[6 7 8]
 [1 2 3]
 [9 3 2]]
3
[8 3]
[9 3 2]
[9 3]
[[7 8]
 [2 3]
 [3 2]]


In [90]:
#Iterate through a array
a=np.array([[6,7,8],[1,2,3],[9,3,2]])
print(a)

#to iterate through rows
for row in a:
    print(row)
    
#to flattern the array 
for cell in a.flat:
    print(cell)

a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
print(a,b)

#to stack them in vertical manner
print(np.vstack((a,b)))
#Horizontal stack
print(np.hstack((a,b)))



[[6 7 8]
 [1 2 3]
 [9 3 2]]
[6 7 8]
[1 2 3]
[9 3 2]
6
7
8
1
2
3
9
3
2
[[0 1]
 [2 3]
 [4 5]] [[ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [96]:
#Spliting the array
a=np.arange(30).reshape(2,15)
print(a)

#Horizontal split 
print(np.hsplit(a,3)) #since the output is not clearly visible, we goona store it in a variable
result = np.hsplit(a,3)
print(result[0])
print(result[1])
print(result[2])

#Vertical split
result=np.vsplit(a,2)
print(result[0])
print(result[1])



[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
[array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]
[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [25 26 27 28 29]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [103]:
#Indexing with boolean arrays

a=np.arange(12).reshape(3,4)
print(a)

b=a>4
print(b) #prints true/false based on the number and the operation given

print(a[b])# it looked at the 'a' array and gave output which are all greater than 4

a[b]=-1 # it will replace the numbers which are all greater than 4
print(a)




[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4 -1 -1 -1]
 [-1 -1 -1 -1]]


In [104]:
#Numpy tutorial -- read write text files
#write a file
x=np.array([[1,2,3],[4,5,6],[7,8,9]],np.int32)
np.savetxt("test.txt",x)

In [105]:
#Read file
y=np.loadtxt("test.txt")
print(y)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [108]:
#Numpy Tutorial -- iterate numpy array using nditer
import numpy as np
a=np.arange(12).reshape(3,4)
print(a)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [110]:
#To iterate write the for loop
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [111]:
#To print individual elements in the numpy array

for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [112]:
#To print individual elements in the numpy array with flattern format

for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [115]:
#using nditer to flattern
for x in np.nditer(a,order='C'):#for printing column by column
    print(x)


0
1
2
3
4
5
6
7
8
9
10
11


In [116]:
for x in np.nditer(a,order='F'):#for printing row by row
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [118]:
#external loop creates a column
for x in np.nditer(a,order='F',flags=["external_loop"]):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [122]:
for x in np.nditer(a,op_flags=['readwrite']):#
    x[...]=x*x
print(a)

[[        0         1       256      6561]
 [    65536    390625   1679616   5764801]
 [ 16777216  43046721 100000000 214358881]]


In [125]:
b=np.arange(3,15,4).reshape(3,1)
print(b)

[[ 3]
 [ 7]
 [11]]


In [126]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
256 3
6561 3
65536 7
390625 7
1679616 7
5764801 7
16777216 11
43046721 11
100000000 11
214358881 11
